//works
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab5tf(
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,
	input 		     [1:0]		KEY,
	output		     [9:0]		LEDR,
	input 		     [9:0]		SW
);

 wire [9:0] SWR;
 simple_debouncer bouncer (.clk(MAX10_CLK1_50), .button_in(SW[9:0]), .button_out(SWR[9:0]));
 //assign SWR = SW;

 
wire [15:0] N_wire;
wire [15:0] rResult;

reg [4:0] addrcounter = 5'b0000;

always @ (negedge KEY[1] or negedge KEY[0]) begin
if (!KEY[0])
addrcounter = 5'b0000;
else
addrcounter = addrcounter + 1;
end


ram_16x4 uut0 (.clk(MAX10_CLK1_50), .addr(addrcounter), .mwr(1'b0), .mdi(16'd0), .mdo(N_wire));


 top_level uut1 (.clk(MAX10_CLK1_50), .reset(KEY[0]), .x(N_wire), .key(SWR[1:0]), .y(rResult), .done(LEDR[0]));

 
 hexdisplay hex0 ( .X(rResult[3:0]), .Y(HEX0));
 hexdisplay hex1 ( .X(rResult[7:4]), .Y(HEX1));
 hexdisplay hex2 ( .X(rResult[11:8]), .Y(HEX2));
 hexdisplay hex3 ( .X(rResult[15:12]), .Y(HEX3));

 
 hexdisplay hex5 ( .X(addrcounter), .Y(HEX5));


 
 endmodule
 
 